### ISSUE TITLE
Feature request: manifest addition & subtraction

### ISSUE THREAD

**Issue by trshafer** [manifestival/manifestival#41]
It would be helpful to have a `Without` and an `Add` function to the manifest. It will allow the manifests to be logically separated into categories and then combined in logic specific ways.

Example:

```
subManifest := manifest.Filter(CRDs).Filter(RBAC)
withoutRbacOrCRDs = manifest.Without(subManifest)
withoutRbacOrCRDs.Apply();
```

```
subManifest := manifest.Filter(CRDs)
subManifest2 := subManifest.Add(manifest.Filter(RBAC))
subManifest2.Apply()
```

I'm thinking the logic would filter on equality of `apiVersion && Kind && Namespace && Name`

**Comment by jcrossley3** [comment]
Thanks for the suggestions!

I'm going to assume that by `Filter(CRDs).Filter(RBAC)` you meant `Filter(CRDs, RBAC)` in your example since the former wouldn't find any RBAC resources among those CRD's. Filter chaining works, but it's superfluous unless the upstream results include things the downstream filters are looking for.

That being said, the behavior of `Without` is very similar to the `None` predicate. So you could refactor your first example with the `Any` predicate. Something along these lines:
```
clusterScoped := Any(CRDs, RBAC)
clusterResources := manifest.Filter(clusterScoped)
namespaceResources := manifest.Filter(None(clusterScoped))
```
We could also introduce a `Without` filter function that takes a manifest and only returned resources not present in it. Something like this:
```
subManifest := manifest.Filter(CRDs, RBAC)
withoutRbacOrCRDs = manifest.Filter(Without(subManifest))
withoutRbacOrCRDs.Apply()
```

So I feel like we already have `Without` covered since it essentially "filters" the manifest, but `Add` is different. Because it would expand the manifest, neither `Filter` nor `Transform` really covers that use case. It's still essentially syntactic sugar around this, though:
```
mf3 := ManifestFrom(Slice(append(mf1.Resources(), mf2.Resources()...)))
```

**Comment by trshafer** [comment]
Thanks for the examples. I think these are good Readme examples. 

I agree that the `Without` example is not a significant improvement from the `None` syntax. Only `Filter` and `Transform` are really documented, so adding an example of `Any` and `None` are helpful.

Now that I see `ManifestFrom` example, I could take it or leave it on `Add`. I'm leaning towards it being helpful syntatic sugar as remembering the code is significantly different opposed to `Without` vs `None`.

**Comment by jcrossley3** [comment]
Sorry the docs took so long. Feel free to re-open if they're insufficient. Thanks!

**Comment by trshafer** [comment]
Thanks Jim. These docs are fantastic.

**Comment by jcrossley3** [comment]
Re-opening because I think the "option-forwarding awkwardness" justifies the addition of an `Append` function. I prefer that name to `Add` because it implies an ordering, just as you would in a YAML file. So in the case of "equal" resources (same `apiVersion` `Kind` `Namespace` and `Name`) the last one will "win".
