### ISSUE TITLE
Don't inject cross-namespace OwnerReferences

### ISSUE THREAD

**Issue by polivbr** [manifestival/manifestival#82]
Kubernetes v1.20+ does not support cross-namespace OwnerReferences and will garbage collect the child resource due to an OwnerRefInvalidNamespace.

Along with bypassing ownership injection for cluster-scoped resources, InjectOwner() should also bypass injecting ownerships when the resource and the owner are in different namespaces.

**Comment by jcrossley3** [comment]
I don't want to do this, mainly because I'd like to trust developers to manipulate the manifest however they see fit. It's their responsibility to apply a valid manifest, and it's the responsibility of k8s to return an error for an invalid one.

I'd hate to have to cut another release just because we prevent the behavior now, and k8s decides to allow it in the future.
